In [13]:
import numpy

# **Lab 1 - Introduction to Python**

Python is a *dynamic* and *interpreted* programming language. This means that variables of any type (numbers, characters, lists, etc.) can be created without the need to specify their type; additionally, the type of an object can *change* dynamically across the code.

Like in other programming languages, a code written in Python is composed of a sequence of instructions. By convention, **each line of code is an instruction** (no semicolon needed!). 
</br>
</br>
Roughly speaking, there are two different environments where one can write (and then execute) Python instructions:

1. Python **scripts** (files ".py"). They are the standard working environment. By launching a script, all the instructions inside it are executed (in sequence). We will see examples of this later.

2. Python **notebooks** (files ".ipynb"). Useful for educational and illustrative purposes, notebooks allow one to create a working session during which the user can execute various instructions, usually grouped into *cells*. The order of execution is determined by the user.
In particular, unlike scripts, notebooks allow the user to *interact* with the software. The session remains active until the user interrupts or restarts the runtime.

What we are using now is a notebook. There are *text cells* (like this one) and *code cells* (like the one below). Code cells can be executed with a mouse click or by pressing "shift+enter".

Within the code, using the "#" symbol, we can also insert **comment lines**. They do not constitute instructions to be executed but are helpful for those reading the code.

# **Simple and Composite Variables, Functions**

## Numeric variables

In [14]:
# Declaring, operating and printing



<mark>**ATTENTION!** (Floating point)</mark></br>
We must not forget that all operations are carried out within a computer, which inevitably uses *finite arithmetic*. This means that:
- each number can be represented up to a certain level of precision; beyond that level, distinct numbers can become indistinguishable.
- every operation, no matter how simple it may seem, can generate small calculation errors, which can propagate within the code.

In [15]:
x = 1
y = 1.0000000000000000000000000000000001

x == y

True

In [16]:
y = 10.05
(x+y)**2 - x**2 -y**2 -2*x*y # should return 0.

7.105427357601002e-15

## Strings

In addition to numeric variables, another very useful object are **strings**, which are sequences of characters.

By using the formatting operator **%** along with placeholders like **%d** (integers), **%f** (floats), **%e** (exponential notation), we can construct strings containing the values of numeric variables.

## Lists and Tuples

Other useful concepts are those of lists and tuples. Both are composite objects, meaning *they contain other objects*.
In general, both lists and tuples can contain objects of different types.

Let's start by looking at the case of **lists**.

In [17]:
# Declare, access, length, assign, append, concatenate, multiply




**Tuples** are similar to lists, but they are *immutable*. Therefore, once created, they cannot be modified.

In [18]:
# Declaring and using for assignment




## Functions

Another very useful concept is that of a **function**. In Python, a function is an object that produces outputs based on certain inputs.
</br></br>
To create a function, we use the **def** command followed by the list of required inputs (in parentheses) and the sequence of operations defining the function.

Note: all instructions that are part of the *body* of the function must be written **below** the definition of the function itself and followed by appropriate **indentation**.

A function can perform various calculations within its body: the only results that will be returned (and visible) are those preceded by the **return** command.

**Note**: By leveraging the concept of *tuple*, we can build functions that return multiple outputs simultaneously.

Finally, when defining a function, we may also specify whether some inputs are *optional*, that is: the user can pass a value, but it is not mandatory. If not provided, a default value will be used. The syntax is as follows:

In the future, we will see that it is also possible to define functions with an unspecified number of inputs. But, for now, that's too early!

<mark>**Exercise 1**</mark></br>
Create a function called $\textsf{padding}$ that, given a list L and an integer n, returns an "augmented" version of L with n additional zeros. That is, the function should operate as follows:

    padding([3,4,'ciao'], 5) --> [3,4,'ciao',0,0,0,0,0]
    padding(['u',1], 3) --> ['u',1,0,0,0]

Hint: Avoid using the *append* method. Instead, leverage the + and * operators.


In [19]:
# Exercise 1






# **Flow control**

## *For* loop
The for loop is a way to ensure that certain instructions are repeated for a predetermined number of times. Each iteration is driven by a *counter*, which varies within a predefined range of values.

As with functions, the entire body of the for loop must be written **below** the loop declaration together with a proper **indentation**.

In general, the counter of a for loop can vary within any *iterable* object: a list, a tuple, etc.

In particular, we can construct standard iterators using the **range** command.

## *While* loop
Sometimes, it is useful to **repeat a set of instructions as long as a certain condition is met**. In particular, we want to repeat a certain block of instructions without knowing the total number of repetitions in advance (otherwise, we could use a for loop!).

We can achieve this with the *while* loop: see the example below.

## Conditional statements: *if* and *else* commands
In some cases, we may want the code to execute certain instructions only under certain circumstances. In particular, we want to do a given thing if a certain condition is met (if); otherwise (else), we would like an operation to occurr.

Again, it is important to **pay attention to the indentation of the code**. The latter, in fact, determines which instructions fall under a branch and which do not.

To handle multiple conditions simultaneously, you can use the **and** and **or** keywords.

<mark>**Exercise 2**</mark></br>
Write a function that, given a numerical value $x$, returns $x$ if $x\ge0$, and 0 otherwise.

*Curiosity*: in Machine Learning, this function is so famous that people have come up with a specific name for it. </br>It is commonly known as Rectified Linear Unit (ReLU).


In [20]:
# Exercise 2





<mark>**Exercise 3**</mark></br>
Write a function that, given a list of numbers, returns their arithmetic mean.



In [21]:
# Exercise 3





<mark>**Exercise 4**</mark></br>
Try to determine the smallest value $\epsilon>0$ such that, in finite arithmetic, $1+\epsilon$ is different from $1$.

Hint: use a while loop!

In [22]:
# Exercise 4





# **Python Packages**: numpy and matplotlib
Fortunately, there are already many Python functions available online that we can directly **import** and **use**. Generally, these functions are collected within *packages*, which can be imported using the **import** command.
</br></br>
Today, we will take a quick look at 2 packages:

- **numpy**, for handling arrays (vectors, matrices, etc.);
- **matplotlib**, for visualizing plots.

## Numerical Analysis in **numpy**
Numpy is a package that allows you to build and work with numerical arrays (and more).
</br></br>
In general, arrays are similar to lists, but having much more structure, they support many more operations.

In [23]:
# Importing and using basic functions from the package




In [24]:
# Numpy arrays (pt. 1)




**Note**: If we want to learn more about a particular function (how it works, what inputs it accepts, what it returns, etc.),</br> we can use the *help* command.

In [25]:
help(numpy.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.

The main differences between arrays, lists, and tuples are:
- Arrays have a fixed size (lists do not).
- Values inside an array can be modified (not true for tuples).
- Arrays can become specialized if their elements are all of the same type.

Regarding the last point: we will be interested in **numeric arrays**, which have many useful properties. Let's explore some of them.

In [26]:
x = numpy.array([1, 4, 5, -2, 1, 0]) # <--- creating an array from a list using the 'array' method
y = numpy.linspace(-1, 1, 6)
z = numpy.array([1, -2])

In [27]:
print(y)
print(x+y)
print(x*y)

[-1.  -0.6 -0.2  0.2  0.6  1. ]
[ 0.   3.4  4.8 -1.8  1.6  1. ]
[-1.  -2.4 -1.  -0.4  0.6  0. ]


In [28]:
print(z)
print(2.0*z)
print(z + 5.0)
print(z**2.0)

[ 1 -2]
[ 2. -4.]
[6. 3.]
[1. 4.]


In general, the convention is to perform operations **component-wise**. This can be done as long as the arrays involved have compatible dimensions.

In [30]:
#x+z

The size of an array can be checked using the *shape* attribute.

In [31]:
print(x.shape)
print(z.shape)

(6,)
(2,)


In general, the *shape* of an array is a tuple, as an array can have multiple dimensions.

In [32]:
x = numpy.array([1, 2, -4]) # <-- 1D array (vector)
A = numpy.array([[5, 6], [1, 0], [8, 3]]) # <-- 2D array 2D (matrix)
T = numpy.array([[[1,2,3,5], [7,8,9,10]], [[0,0,0,0], [3,1,-1,1]]]) # <-- 3D array (tensor)

In [33]:
print("x = ")
print(x)
print("\nA =")
print(A)
print("\nT =")
print(T)

x = 
[ 1  2 -4]

A =
[[5 6]
 [1 0]
 [8 3]]

T =
[[[ 1  2  3  5]
  [ 7  8  9 10]]

 [[ 0  0  0  0]
  [ 3  1 -1  1]]]


In [34]:
print("shape of x = ")
print(x.shape)
print("\nshape of A = ")
print(A.shape)
print("\nshape of T = ")
print(T.shape)

shape of x = 
(3,)

shape of A = 
(3, 2)

shape of T = 
(2, 2, 4)


We will mainly be interested in 1D arrays (vectors) and 2D arrays (matrices). With these, we can perform most of the standard
operations of linear algebra.</br>Let's see some of them.

In [35]:
A

array([[5, 6],
       [1, 0],
       [8, 3]])

In [36]:
A.T # <-- transpose

array([[5, 1, 8],
       [6, 0, 3]])

In [37]:
B = numpy.array([[1,  5],     # <-- let's use spacing to our advantage to simplify code comprehension!
                 [-1, 8],
                 [0,  0]])

B

array([[ 1,  5],
       [-1,  8],
       [ 0,  0]])

In [38]:
A+B

array([[ 6, 11],
       [ 0,  8],
       [ 8,  3]])

In [39]:
# Componentwise multiplication, vs Matrix multiplication





During the labs, we will explore many numpy functions. For today, we shall start by learning just a couple of them:

In [40]:
numpy.zeros((2, 3)) # <-- array full of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
numpy.ones((2, 3)) # <-- array full of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
numpy.arange(3, 8) # <-- discrete sequence from 3 to 8 (top extreme EXCLUDED!)

array([3, 4, 5, 6, 7])

In [43]:
numpy.diag([1, 2, 5]) # <-- matrix with a given diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 5]])

In [44]:
C = numpy.array([[1, 1],
                 [4, 5]])

numpy.diag(C) # <-- or, it can be used to extract a diagonal from a given matrix

array([1, 5])

In [45]:
numpy.eye(3) # <-- identity matrix of a given size

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
A.reshape((1, 6)) # <-- re-organizes the elements within the array into a predetermined configuration

array([[5, 6, 1, 0, 8, 3]])

In [47]:
A.reshape((2, 3))

array([[5, 6, 1],
       [0, 8, 3]])

Numpy arrays also support *componentwise* evaluation of classical mathematical functions, such as sine, cosine, exponential, etc.

In [48]:
x = numpy.array([1.0, 3.0])
numpy.sin(x)

array([0.84147098, 0.14112001])

In [49]:
numpy.cos(x)

array([ 0.54030231, -0.9899925 ])

In [50]:
numpy.exp(x)

array([ 2.71828183, 20.08553692])

In [51]:
numpy.log(x)

array([0.        , 1.09861229])

Lastly, aside from functions, numpy also comes with other stuff, such as numerical constants, e.g., $\pi$.

In [52]:
numpy.pi

3.141592653589793

<mark>**Exercise 5**</mark></br>
Leveraging numpy, create a function that, given a positive integer $n$, creates a square matrix $n\times n$ defined as:</br></br>

$$H = \left[\begin{array}{ccccc}
1 & 2 & ... & ... & n\\
n+1 & n+2 & ... & ... & 2n\\
... & ... & ... & ... & 3n\\
... & ... & ... & ... & ..\\
... & ... & ... & ... & n(n-1)\\
... & ... & ... & ... & n^2\\
\end{array}\right]$$
</br>
Hint: try messing around with the functions *arange* and *reshape*!

In [64]:
import numpy as np

In [67]:
# Exercise 5

def n_rows(row):
    H = np.arange(row**2)
    H = np.reshape(H, (row, row))
    return H


In [68]:
n_rows(5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

<mark>**Exercise 6**</mark></br>
Create a function that, given a matrix $A$ and a nonnegative integer $n\ge0$, computes the $n$th power of $A$ *in the matrix sense*.

In [54]:
# Exercise 6






A very useful concept in numpy (and many other packages) is *recycling*. By leveraging basic properties of tensors, recycling can be used to compute "cross" operations in a very natural way. Since the idea is more easy to understand than to explain, we report a few examples below

Essentially, the idea is that we can always do "componentwise operations" if we make two tensors have compatible shapes. Two shapes $(s_1,\dots, s_m)$ and $(s'_1,\dots,s'_m)$ are compatible if for all $i=1,\dots,m$ one has either $s_i=s'_i$ or $s_i=1$ or $s_i'=1$. The 1's are those that enable the recyling effect.

<mark>**Exercise 7**</mark></br>
Create a function that, given two clouds of $d$-dimensional points, $[p_1; \dots; p_n]$ and $[q_1;\dots; q_m]$, computes the shortest distance between the two, i.e. $\min_{i,j}\|p_i-q_j\|$, where $\|\cdot\|$ is the Euclidean norm. To this end, assume that the two collections of points are stored in two matrices $\mathbf{P}\in\mathbb{R}^{n\times d}$ and $\mathbf{Q}\in\mathbb{R}^{m\times d}$, respectively.

In [81]:
def min_distance(p, q):
    diff = p - q
    dist = np.abs(diff)
    return np.min(dist), np.argmin(dist)

In [83]:
p = np.random.rand(2, 2)
q = np.random.rand(2, 2)
print(p) 
print(q)

min_distance(p, q)

[[0.44740941 0.97258226]
 [0.03913376 0.94668461]]
[[0.81968899 0.99290025]
 [0.41186416 0.98573661]]


(np.float64(0.020317992757383108), np.int64(1))

## Drawing graphs with **matplotlib**

A well-known library for graphs visualization is **matplotlib**. In particular, its submodule **matplotlib.pyplot**.

Given that the name is lenghty, people usually import it with a suitable pseudonym (typically **plt**).</br>
Note: numpy also has a classical pseudonym, which is **np**.

The main functions we are interested in are
- **figure**: creates an empty figure (not mandatory, but it allows choosing stuff such as the figure size);
- **plot**: draw lines / points with certain coordinates;
- **legend**: add a legend;
- **title**: add a title;
- **show**: show the graph (not mandatory, but useful for suppressing unwanted outputs).

Obviously there are many others, but we will see them during the course.

In [55]:
# Plotting function graphs






<mark>**Exercise 8**</mark></br>
Draw the graph of $f(x) = \cos(x)$ for $x\in[-\pi, \pi]$, using default settings (continuous line). Precisely, within the same plot, draw the same function three times, where each drawing refers to a different spatial grid: start with a grid $\mathbf{x}$ consisting of 5 points, then 10, and finally 100.

Try also repeating this by using the marker "-o" for the coarsest curve (5 knots).

In [56]:
# Exercise 7






# **Extras**
The subsections below include some extra Python stuff. Part of it will be explained during the course, while the rest is there for the curious ones!

## List comprehension
In Python, we can combine the syntax of **list definition** with that of **for loop** to construct lists in a very compact way

In [57]:
A1 = [0, 1, 4, 9, 16]
A2 = [i**2 for i in range(5)]
print(A1)
print(A2)

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]


In [58]:
[chr(i) for i in range(65, 71)]

['A', 'B', 'C', 'D', 'E', 'F']

## Raising errors and handling exceptions

When something goes wrong, we can raise errors with the command **raise**. In general, errors can be of many different types. The standard one is *RuntimeError*. An example is provided below.

In [59]:
# Given an integer n, the following function computes the factorial n! by iteratively multiplying 1*2*...*n.
# However, if n is negative or decimal, we should abort the procedure (the factorial can be generalized to such n,
# but the definition is not this one anymore!)

# Standard implementation
def factorial(n):
  x = 1
  for k in range(1, n+1):
    x = x*k
  return x

In [60]:
factorial(0), factorial(1), factorial(2), factorial(3)

(1, 1, 2, 6)

In [61]:
factorial(-1) # This is wrong!

1

In [62]:
# Better implementation
def factorial(n):
  if(n<0):
    raise RuntimeError("Negative value detected: n needs to be a positive integer!")
  x = 1
  for k in range(1, n+1):
    x = x*k
  return x

In [63]:
factorial(-1)

RuntimeError: Negative value detected: n needs to be a positive integer!

Errors can be handled using the **try / except** syntax, which allows us to specify a pre-determined behavior when an exception is encountered.



In [ ]:
# Example: the following syntax doesn't work
sum(["a", "b", "ciao"])

In [ ]:
# Whereas the following is ok
sum([-1, 2, 8, 11])

In [ ]:
# We can fix this with our own "sum" function, implementing a try / except block

def newsum(L):
  try:
    return sum(L)                  # <-- First, we try the usual approach

  except TypeError as error:       # <-- if that doesn't work, we attempt a for loop implementation
    k = L[0]
    for obj in range(1, len(L)):
      k += obj
    return k

## Complex numbers

Python (and numpy) can also work with complex numbers. These are represented using the letter **j**. The syntax is as follows

In [84]:
z = 3+4j
print(z)

(3+4j)


In [85]:
z**2

(-7+24j)

In [86]:
z.real, z.imag

(3.0, 4.0)

## Classes

Python supports object-oriented-programming, a paradigm in which one can define "custom object types", each of which:

- can have multiple attributes (much like "structures" in C or Matlab);
- may come with its own methods, i.e., functions owned by the object.

The following example will quickly clarify the idea.

In [ ]:
# We create a Python class for a new object type called "Polygon".
# Polygons will be characterized by the coordinates of their vertices.
# All Polygon objects will have a method, called "plot", that allows one to plot the Polygon.
# We also include a method, called "lengths", which returns the length of each side in the Polygon

import numpy as np

class Polygon(object): # <-- this line says that "Polygon" is a class made of "objects"
  def __init__(self, list_of_points): # <-- this line specifies how to create a Polygon: we must pass a list of points
    self.points = np.array(list_of_points) # <-- storing as numpy array: it will make things simpler!

  def plot(self):
    x = list(self.points[:, 0]) # <-- list of x coordinates
    y = list(self.points[:, 1])

    # Re-adding the first point to close the loop
    x = x + [self.points[0][0]]
    y = y + [self.points[0][1]]

    plt.fill(x, y)

  def lengths(self):
    n = len(self.points)
    return [np.linalg.norm(self.points[i]-self.points[(i+1) % n ]) for i in range(n)]

# NB: in the lines above, "self" is a formal reference to the object itself.
# Without it, we would not be able to "use" the object itself inside the methods!

In [ ]:
square = Polygon([[0, 0], [0, 1], [1, 1], [1, 0]])
square.points

In [ ]:
square.lengths()

In [ ]:
plt.figure(figsize = (4,4))
square.plot()

One can also create **nested classes** to develop objects that become more and more specific.

Ex: we can create a subclass of Polygon called $\textsf{Triangle}$, which we can further enrich we new methods specific for triangles.

In [ ]:
import numpy as np
class Triangle(Polygon):   # <-- we are saying that all Triangles are also Polygons: in this way,
                           #     methods such as .__init__ or .plot are inherited and directly available!

  def area(self):
    a, b, c = self.lengths() # Lenghts of the three segments
    return triangle_area(a, b, c)

In [ ]:
square.area() # this is NOT a "Triangle object", so it should not have an "area" method implemented

In [ ]:
triangle = Triangle([[0,0], [0,2], [1,0]])
triangle.area()

In [ ]:
plt.figure(figsize = (4,4))
triangle.plot()
plt.axis("square")
plt.show()

<mark>**Exercise 9**</mark></br>
Create a new class called $\textsf{Circle}$. Object of this class should be characterized by two attributes: the center and the radius. Make sure to implement a "plot" method as well.

<mark>**Exercise 10**</mark></br>
Modify the definition of the $\textsf{Triangle}$ class by including a new method called $\textsf{inner\_circle}$ which, when called, returns the inscribed circle (as an object of the new class $\textsf{Circle}$). To check whether things work properly, try plotting a triangle together with its inscribed circle.